package com.rainbow_universe.bettercode.core;

public enum RuntimeErrorCode {
    PARSE_SCHEMA_MISMATCH,
    SLOT_DESYNC,
    PACKET_SKIP_RETRY_EXHAUSTED,
    MISSING_REQUIRED_ITEM,
    PUBLISH_PAYLOAD_INVALID,
    DOWNLOAD_FAILED,
    PLAN_PARSE_FAILED,
    NO_PENDING_PLAN,
    COMMAND_EXECUTION_FAILED,
    UNIMPLEMENTED_PLATFORM_OPERATION
}
